
### ODA OLUŞTURMAK İSTİYORUM
POST http://localhost:4000/api/createroom
Content-Type: application/json

{
    "times":60,
    "tour":5,
    "usernames":["muaz"],
    "username":"muaz"
}

### ODAYA GİRMEK İSTİYORUM
POST http://localhost:4000/api/loginroom
Content-Type: application/json

{
    "key":"6325bfee19cdf55e894f9392",
    "username":"muaz4"
}

### Cevap veriyorum
POST http://localhost:4000/api/room/tour
Content-Type: application/json

{
    "key":"63302ce141fb624f42f468c1",
    "username":"muaz",
    "name":"muaz", 
    "city":"manisa", 
    "animal":"maymun", 
    "plant":"manolya", 
    "stuff":"masa"
}

 